name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  codemagic_manager:
    path: ../
  cached_network_image: ^2.4.1
  cupertino_icons: ^1.0.1

flutter:
  uses-material-design: true
